# Global section
checksum:
  name_template: '{{ .Tag }}-{{ time "20060102" }}-checksums.txt'

snapshot:
  name_template: '{{ .Env.PACKAGE_NAME_PREFIX }}-{{ time "20060102" }}'

release:
  disable: true

changelog:
  filters:
    exclude:
      # [skip changelog], [skip-changelog], [changelog skip], [changelog-skip]
      - '^(?i)\[(skip|changelog)[ ,-](skip|changelog)\].*'
      # [skip ci], [skip-ci], [ci skip], [ci-skip]
      - '^(?i)\[(skip|ci)[ ,-](skip|ci)\].*'

# We have multiple builds in order to fine tune
# cross compilations.
builds:
  # -
    # OSX
    # id: arduino-create-agent_osx
    # binary: arduino-create-agent
    # env:
    #   - CGO_ENABLED=1
    #   - CXXFLAGS="-mmacosx-version-min=10.15"
    #   - CC=/usr/x86_64-apple-darwin14/bin/cc
    #   - MACOSX_DEPLOYMENT_TARGET=10.10
    # goos:
    #   - darwin
    # goarch:
    #   - amd64
    # ldflags:
    #   - -s -w -X github.com/arduino/arduino-create-agent/version.versionString={{.Tag}} -X github.com/arduino/arduino-create-agent/version.commit={{ .ShortCommit }}
  # -
  #   # ARM
  #   id: arduino-create-agent_arm
  #   binary: arduino-create-agent
  #   env:
  #     - CGO_ENABLED=1
  #     - CC=/usr/arm-linux-gnueabi/bin/cc
  #   goos:
  #     - linux
  #   goarch:
  #     - arm
  #   goarm:
  #     - 6
  #   ldflags:
  #     - -s -w -X github.com/arduino/arduino-create-agent/version.versionString={{.Tag}} -X github.com/arduino/arduino-create-agent/version.commit={{ .ShortCommit }}
  #     - "-extldflags '-static'"
  # -
  #   # ARMv7
  #   id: arduino-create-agent_armv7
  #   binary: arduino-create-agent
  #   env:
  #     - CGO_ENABLED=1
  #     - CC=/usr/arm-linux-gnueabihf/bin/cc
  #   goos:
  #     - linux
  #   goarch:
  #     - arm
  #   goarm:
  #     - 7
  #   ldflags:
  #     - -s -w -X github.com/arduino/arduino-create-agent/version.versionString={{.Tag}} -X github.com/arduino/arduino-create-agent/version.commit={{ .ShortCommit }}
  #     - "-extldflags '-static'"
  # -
  #   # ARM64
  #   id: arduino-create-agent_arm64
  #   binary: arduino-create-agent
  #   env:
  #     - CGO_ENABLED=1
  #     - CC=/usr/aarch64-linux-gnu/bin/cc
  #   goos:
  #     - linux
  #   goarch:
  #     - arm64
  #   ldflags:
  #     - -s -w -X github.com/arduino/arduino-create-agent/version.versionString={{.Tag}} -X github.com/arduino/arduino-create-agent/version.commit={{ .ShortCommit }}
  #     - "-extldflags '-static'"
  -
    # All the other platforms
    id: arduino-create-agent
    binary: arduino-create-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w -X github.com/arduino/arduino-create-agent/version.versionString={{.Tag}} -X github.com/arduino/arduino-create-agent/version.commit={{ .ShortCommit }}
      - "-extldflags '-static'"

archives:
  -
    id: "arduino-create-agent"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64bit
      # darwin: macOS
      386: 32bit
      arm: ARM
      arm64: ARM64
      linux: Linux
      windows: Windows
    files:
      - LICENSE.txt
